name: MegaLinter
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: MegaLinter
        uses: oxsecurity/megalinter@v7.11.1
      - name: SonarCloud Scan for C and C++
        uses: SonarSource/sonarcloud-github-c-cpp@v2.0.2
        with:
          installation-path: .sonar
          cache-binaries: true
          
